---
- hosts: appserver
  become: yes
  tasks:
    - name: get latest packages
      action: apt update_cache=yes
    - name: Install npm
      apt: name=npm state=installed update_cache=true state=latest
    - name: Install nodejs
      apt: name=nodejs update_cache=true state=latest
    - name: Create symlink for nodejs
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    - name: Install git
      apt: name=git update_cache=true state=latest
    - name: Clone the git repo
      git: repo=https://github.com/ankitkumar93/WebApp.git dest=/root/WebApp
